name: Generate Tag


permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get version from package.json
        id: package
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Create tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag v${VERSION}
          git push origin v${VERSION}
